### ISSUE TITLE
Latest Docker image not running in foreground

### ISSUE THREAD

**Issue by squidfunk** [esl/MongoosePush#19]
The latest Docker image on DockerHub terminates after initializing:

```
mongoosepush_1  | 19:10:29.817 [info] Application elixometer started on node 'mongoose_push@127.0.0.1'
mongoosepush_1  | 19:10:29.817 [info] Application exometer started on node 'mongoose_push@127.0.0.1'
mongoosepush_1  | 19:10:29.817 [info] Application cowlib started on node 'mongoose_push@127.0.0.1'
mongoosepush_1  | 19:10:29.818 [info] Application ranch started on node 'mongoose_push@127.0.0.1'
mongoosepush_1  | Interactive Elixir (1.4.1) - press Ctrl+C to exit (type h() ENTER for help)
mongoosepush_1  | Eshell V8.3  (abort with ^G)
mongoosepush_1  | iex(mongoose_push@127.0.0.1)1> *** Terminating erlang ('mongoose_push@127.0.0.1')
ejabberd_mongoosepush_1 exited with code 0
```

docker-compose.yml:

``` yaml
version: '2'
services:
  mongoosepush:
    image: mongooseim/mongoose-push:latest
    ports:
      - "8443:8443"
    environment:
      PUSH_FCM_APP_KEY: "..."
      PUSH_LOGLEVEL: debug
    volumes:
      - ./push:/opt/app/priv
```

This issue seems to be introduced with the following commit: https://github.com/esl/MongoosePush/commit/41d8f4170cc98826219b9de45227a0ea79646c41. This commit included a whole rewrite of `Dockerfile.release`. When I override the `command`, MongoosePush stays in the foreground, thus everything works again as expected:

``` yaml
command: foreground
```

And another question: would it be possible to do proper releases using semantic versioning? We are using this image in production and being only able to pull `latest` (or some PRs) is kind of a deal-breaker.
