### ISSUE TITLE
PUSH_LOGLEVEL is ignored

### ISSUE THREAD

**Issue by squidfunk** [esl/MongoosePush#22]
I cannot set the log level via environment. This is my configuration:

``` yaml
version: '2'
services:
  mongoosepush:
    image: mongooseim/mongoose-push:latest
    ports:
      - "8443:8443"
    environment:
      PUSH_FCM_APP_KEY: "..."
      PUSH_LOGLEVEL: error
    volumes:
      - ./push:/opt/app/priv
```

When defining `error` I would assume that no `info` messages are logged, but this is the case:

```
mongoosepush_1  | 
mongoosepush_1  | 19:10:29.805 [info]  Setup running ...
mongoosepush_1  | 
mongoosepush_1  | 
mongoosepush_1  | 19:10:29.807 [info]  Directories verified. Res = :ok
mongoosepush_1  | 
mongoosepush_1  | 
mongoosepush_1  | 19:10:29.808 [info]  Setup finished processing hooks (Mode=:normal)...
mongoosepush_1  | 
mongoosepush_1  | 
mongoosepush_1  | 19:10:29.819 [info]  Starting Elixir.MongoosePush.Router with Cowboy on https://0.0.0.0:8443
mongoosepush_1  | 
mongoosepush_1  | 19:10:29.828 [info]  Starting FCM pool with API key ...
mongoosepush_1  | 19:10:29.790 [error] Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.1110.0> exit with reason normal in context child_terminated
mongoosepush_1  | 19:10:29.802 [info] Application lager started on node 'mongoose_push@127.0.0.1'
mongoosepush_1  | 19:10:29.803 [info] Application asn1 started on node 'mongoose_push@127.0.0.1'
```

There also some error with `Elixir.Logger.Supervisor` which may be related.
